---
title: "Basic R"
output: html_notebook
---

# Basic R

## Writing in R and Rmarkdown

This is what I am going to say today.

### Chatting with R

### Rmarkdown tricks

- Bold/Italics
- What if I need special characters?
- Latex (Math)
- Code blocks
    - Keyboard shortcuts
    - Changing code block output

## Variables

### The assignment operator

### Numerics

**Doubles**
**Integers**

Here is a useful cheatsheet for the different numeric operators and how they behave.
  
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

data.frame(
  a = rep(10, 7),
  b = rep(3, 7),
  operator = c('+', '-', '*', '/', '^', '%/%', '%%')
  ) %>%
  mutate(
    ex = paste(a, operator, b),
    result = ex %>%
      map(rlang::parse_expr) %>%
      map(eval) %>%
      unlist() %>%
      round(3) %>%
      formatC(digits = 3, format = 'f', drop0trailing = T)
  ) %>%
  select(-a, -b) %>%
  knitr::kable(
    col.names = c('Operator', 'Expression', 'Result'),
    align = 'c')
```
  
**Why care about the difference?**


###Characters
    - `paste()`
    - `paste0`
    
### Booleans
    - What are they?
    - Nested booles
    - `as.numeric`

### Special types
    - `NA`
    - `NaN`
    - `Inf`

## Vectors

- Two ways to make a sequence, `:` and `seq()`
- Sequence math with a constant
- Sequence math with another sequence
    - Equal size
    - Unequal size
- Accessing sequence elements
    - Only 1
    - Sequence ofdesired elements
    - Numeric collection
    - Booleans
- Letter sequences

## Lists

<We'll fill this section in later, when you need it. For now, they are just a fancy kind of vector.>

## Dataframes

**Construction**
**Accessing elements inside the dataframe**
  - `$`
  - Rows with numbers
  - Rows with boolean tests
  - Columns with numbers
  - Columns with names
  - Making new columns
**Basic data modification**


### Basic functions
**What are functions?**
**Common functions**
`rnorm()`
`mean()`
`sd()`
**What about missing data?**
**How can I make my own?**

## Packages

**Base R and the need for packages**

**Package installation**

**Package loading**

**Calling functions without loading a package**
