---
title: 'CSP 518 - Exercises: 05 - Joins and tidyr'
date: 'Due: 2019-03-15 @ 11:59pm'
output:
  pdf_document: default
---

## Instructions

1. Make a .Rmd file to complete these exercises.

  - Title it "CSP 518 - Exercises: Intro to R" (in quotes)
  - Add your name(s) in the author slot (in quotes)
  - The output can be either be `pdf_document` or `html_document` (no quotes)

2. Turn in just your .Rmd file on Blackboard. Note, I will need to be able to `knit` it myself, so make sure everything runs the way you intend, before you turn it in.

3. For clarity, write "## Question <number>" befor each question to signal which one you are answering.

## Exercises

1. Here are two example dataframes from two different time points. Some participants only have data for time 1, where we measured baseline scores. Others have data for only time two, where we measured followup scores. Merge the dataset so that everyone is included, regardless of how many time points they have data for.

```{r}
set.seed(314159)

time1_df <- data.frame(id = 1:10, baseline = rpois(10, 10))
time2_df <- data.frame(id = 5:14, followup = rpois(10, 10))
```

2. Using the same two initial dataframes above, make a new dataframe that includes only people who have data from both time points (baseline and followup).

3. I want to keep everyone who showed up at time 1 (baseline), but I don't want to analyze anyone without a baseline score. Make a new dataset that has everyone from baseline (regardless of whether they have a followup score), but *only* followup scores from people who were present at baseline.

4. I'd really like to know if there is something atypical about people who only completed one time point. Make a new dataframe that includes all the people who completed time 1, but not time 2.

5. The data from #2 are in a wide format, but my analysis needs them to be in long format. Use the `gather()` function to make a convert the dataframe from #2 into a new one that has three columns, "id", "time", and "score". In this dataframe, each participant should have two rows, one for each of their scores.




6. Actually, I changed my mind. Use the `spread()` command to change the dataframe from #5 back into its original format.


